# Generated by Django 5.1.5 on 2025-02-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('languages', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('bookshelves', models.JSONField(blank=True, default=list)),
                ('formats', models.JSONField(blank=True, default=dict)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('copyright', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('translators', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.author')),
            ],
        ),
    ]
